---
title: "Read me: How to reproduce the analyses ?"
author: "A. Ricouard"
date: "2025-07-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This document is a guide for reproducing the analysis performed in the paper Ricouard *et al.* (2025), *What can be done with the ISIS-Fish model of the mixed demersal fishery in the Bay of Biscay? Lessons learned from calibrating and validating a complex model*. It is organised as follows:

*  `input_data` contains the raw data of different sources used to extract reference data tables to be used in the calibration and validation processes.

* `reference_data` contains processed data to be used directly in the calibration and validation processes. It consists in `.rds` files containing reference values for each year, organised in subfolders by variable and species or fleets.

* `R_fun` contains R scripts with the all functions used in the project 

* `main_scripts` contains the core of the project with `.Rmd` scripts containing the code for the analyses of the project. Once executed, the all produce a `.html` file containing results.
